orbs:
  anchore: anchore/anchore-engine@1.6.5
version: 2.1
workflows:
  scan_image:
    jobs:
      - anchore/image_scan:
          image_name: 'docker.io/anchore/anchore-engine:latest'
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
          timeout: '300'
